### ISSUE TITLE
Can this be used as a real frontend for git?

### ISSUE THREAD

**Issue by legendofmiracles** [git-learning-game/oh-my-git#101]
Since this game uses real git internally, would there be a simple way of displaying my git project with oh-my-git? Maybe even have all cards on the bottom, so that you can do some real work?

The reason why I'm asking is that I love the representation of git repos in this game! It shows everything a lot simpler than your normal `git log` does.

**Comment by prochac** [comment]
And you can learn by the real world scenarios then, while using familiar UI.

**Comment by blinry** [comment]
Glad you like the representation, @legendofmiracles! :) Agreed, having a feature to open a real Git repo inside the game would be nice! One reason that prevented us from adding this for now was that for a big number of commits, our graph layouting woud become pretty slow.

There's a trick how you can already do this, as soon as you have the repository on GitHub! :D Open the "emtpy sandbox", add the repo  `git remote add origin git@github.com:user/repo`, and then `git pull` (and often `git checkout master`!) You have been warned! :D

**Comment by legendofmiracles** [comment]
Finally I can experience my git's messiness in it's nicest form 
![image](https://user-images.githubusercontent.com/30902201/117723769-560eef80-b1d2-11eb-9183-2bc991c81203.png)
