### ISSUE TITLE
Keep user's PATH on Linux, to allow running the game in a Nix environment

### ISSUE THREAD

**Issue by blinry** [git-learning-game/oh-my-git#11]
This is a tracking issue for @tasmo's problem that a Git binary installed in /nix/store can't be found (because we reset the `PATH` variable in the game environment).

**Comment by davidak** [comment]
Related: https://github.com/git-learning-game/oh-my-git/issues/16 (not a duplicate)

**Comment by blinry** [comment]
Extending the PATH instead of completely resetting it should fix this problem in Nix. Feel free to confirm! :)

**Comment by tnias** [comment]
Thanks. The PATH problems is now fixed (at least in my nix setup). :rocket:

**Comment by davidak** [comment]
I can confirm it works now. Thank you!
