### ISSUE TITLE
Make parallel commits level grammar mistake

### ISSUE THREAD

**Issue by ThreeHDM** [git-learning-game/oh-my-git#113]
One of the files says

`A small child.
It really loves cats!
It's holding a lollipop.`

The correct pronoun is `He` 

The correct text would be

`A small child.
He really loves cats!
He's holding a lollipop.`

**Comment by poldi1405** [comment]
https://en.wikipedia.org/wiki/Gender_neutrality_in_languages_with_gendered_third-person_pronouns#It_and_one_as_gender-neutral_pronouns

2nd example. The gender of "child" is basically `null`.

**Comment by ThreeHDM** [comment]
Oh I really did not know this. You learn sth every day.
