### ISSUE TITLE
Clone repo level lacks all the instructions

### ISSUE THREAD

**Issue by frenchiveruti** [git-learning-game/oh-my-git#122]
![imagen](https://user-images.githubusercontent.com/1095997/121072567-c431dc80-c7a7-11eb-8861-8d3dd4e95c8d.png)
There's no way to complete this challenge with just ... that

**Comment by n4mr3g** [comment]
I'm guessing that you uploaded the wrong screenshot?

This is the "Cloning a repo" level, and the problem is: what's the repo's URL?

![image](https://user-images.githubusercontent.com/26860329/174496558-059ec231-2b7a-4936-80f5-3628c8fdfdbc.png)

**Comment by frenchiveruti** [comment]
Well, it's been a year... So really no one cared.-
