### ISSUE TITLE
Crashes in windows

### ISSUE THREAD

**Issue by ctlaltdieliet** [git-learning-game/oh-my-git#13]
When I open the game, I see the opening screen but than a crash occurs.
Exit Code 127
SCRIPT ERROR: crash: Invalid call. Nonexistent function 'fatal_error' in base 'SceneTree'.
          At: res://scenes/helpers.gdc:12
ERROR: File must be opened before use.
   At: core/bind/core_bind.cpp:2195
ERROR: call: OS.execute failed: dependencies\windows\git\bin\bash.exe [C:/Users/tomdemoor/AppData/Roaming/git-hydra/tmp/command3154986942] Output: /usr/bin/bash: C:/Users/tomdemoor/AppData/Roaming/git-hydra/tmp/command3154986942: No such file or directory

Exit Code 127
   At: modules/gdscript/gdscript_functions.cpp:803
FATAL ERROR: OS.execute failed: dependencies\windows\git\bin\bash.exe [C:/Users/tomdemoor/AppData/Roaming/git-hydra/tmp/command3154986942] Output: /usr/bin/bash: C:/Users/tomdemoor/AppData/Roaming/git-hydra/tmp/command3154986942: No such file or directory

Exit Code 127
SCRIPT ERROR: crash: Invalid call. Nonexistent function 'fatal_error' in base 'SceneTree'.
          At: res://scenes/helpers.gdc:12
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2135
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:69

**Comment by blinry** [comment]
Thanks for reporting this, @ctlaltdieliet! I could reproduce and fix this. Feel free to try again, and confirm whether this helps. :)

**Comment by ctlaltdieliet** [comment]
It's working! I'm looking forward to see your Fosdem-talk.
