### ISSUE TITLE
no information provided for the remote URL in git clone level

### ISSUE THREAD

**Issue by danielleberre** [git-learning-game/oh-my-git#14]
I just took a look at the game to see if I can use it with my students.

The game looks very nice to learn git.

However, on the level where I need to clone the teacher repo, this is no information regarding the remote, thus I could not continue.
Looks like the information is missing.

I will  check regularly the status of the projet in the upcoming weeks. Looks quite a nice idea.

**Comment by blinry** [comment]
Thanks for reaching out, Daniel! In that level, you can drag the "git clone" card to the label that says teacher, and it will fill in the required information! Let us know whether that works for you! I tried to clarify what to do here a bit more in 7d8c05e, which will end up in the next version we release.

The correct URL in this case is a local one: `../teacher`

**Comment by danielleberre** [comment]
why not simply `teacher`?

**Comment by blinry** [comment]
Also, I'm curious: in which context would you maybe like to use the game? :) If you have any specific wishes in mind, let us know and we can probably account for them!

**Comment by blinry** [comment]
> why not simply `teacher`?

The teacher repository is in the same directory as "your" repository, so you have to go up one level to access it, when you're inside yours. :) But we think it might be nice to fake a better URL, something like `git@timetravel.school:teacher`, in the final game.

**Comment by danielleberre** [comment]
I am a CS professor.

I use currently https://learngitbranching.js.org/ to introduce our students (2nd year and 4th year) to git.

Your game could complement that tool at least for 2nd year students.

**Comment by danielleberre** [comment]
> > why not simply `teacher`?
> 
> The teacher repository is in the same directory as "your" repository, so you have to go up one level to access it, when you're inside yours. :) But we think it might be nice to fake a better URL, something like `git@timetravel.school:teacher`, in the final game.

Yep, I agree it would be better to use a fake remote URL.

**Comment by danielleberre** [comment]
Tried to continue that level.

I should be able to cd to the teacher directory, to commit my changes, but it does not seem to work.

I guess I do not understand how things are supposed to work.

**Comment by blinry** [comment]
In the game, the commands you run/the cards you play are always in the context of the directory of your own repository. A command sequence that solves the level would look somewhat like this:

![image](https://user-images.githubusercontent.com/81277/107120509-4cea4b80-688e-11eb-91da-85542ff6d2f6.png)

But thanks for describing your confusion – we might need to take things slower, or be more specific! :+1:

**Comment by danielleberre** [comment]
ok, I see my mistake.

I use usually 

`git clone url`

But here url is `../teacher`, so it is needed to mention the target directory ...

**Comment by blinry** [comment]
Agreed! So far, we have probably prioritized the "playing cards" interface, which takes care of that automatically. :) Giving more explicit hints about how to do this via the CLI would be great!

**Comment by danielleberre** [comment]
Yep, I do everything using the CLI, because this is what I want to do with our students. They need to use git on the CLI to work on their projects. So we spend the first week "playing" with git concepts, then use it on real projects.

**Comment by davidak** [comment]
using the CLI is also needed to get the golden badge. i only knew it was ../teacher, because i used the card before and looked around with `ls -la ../`

i suggest to add the URL to the task description. show the full command there

![Screenshot from 2021-02-08 03-05-02](https://user-images.githubusercontent.com/91113/107167944-83bd8000-69ba-11eb-933e-63a566d55911.png)

**Comment by blinry** [comment]
Playtesting shows that people are regularly confused by this. We think its best to avoid the clone operation alltogether in the intro chapter, and restructured it so that the repo is already present. We might re-introduce the concept in a later level.

Also, @danielleberre, the current version, 0.6.0, brings in a lot of hints and motivation in the first levels to use the command line. :) The levels have a `[cli]` section now which can be used for such hints.

**Comment by danielleberre** [comment]
@blinry I just downloaded release 0.6: it is indeed much more intuitive for git pull/push. Thanks for improving that part.
