### ISSUE TITLE
Missing Logo in README

### ISSUE THREAD

**Issue by Nishaaaanth** [git-learning-game/oh-my-git#172]
Link to the actual logo of the **Funders** in the README file is not an image

![bug:missing+logo](https://user-images.githubusercontent.com/83387409/229283158-ffacb59b-03a1-4aa7-9ad4-8390afae3df6.png)

**Comment by Gortyser** [comment]
Perhaps this one can be closed.
I can see all logos in the README
![image](https://github.com/git-learning-game/oh-my-git/assets/30402802/2405d63d-075f-4a82-bd14-e9249b8184f0)

**Comment by Nishaaaanth** [comment]
Yes this can be closed.
