### ISSUE TITLE
Rename porject oH my GYATTTT

### ISSUE THREAD

**Issue by smol-shepherd** [git-learning-game/oh-my-git#206]
OH MY GYATTT
![image](https://github.com/git-learning-game/oh-my-git/assets/167160235/599d2035-023c-43d8-9682-110f50e17ee0)

HOW BIg was thAT GYAATTTT
bONNY:
https://cdn.shopify.com/videos/c/vp/ac8dea861dce4be6a0885baaf29ced3b/ac8dea861dce4be6a0885baaf29ced3b.HD-1080p-7.2Mbps-22353958.mp4

**Comment by TruncatedDinoSour** [comment]
make pr

**Comment by blinry** [comment]
Closing and reporting for spam. Please don't do that, this is not cool.

**Comment by voxel-im** [comment]
b
