### ISSUE TITLE
Missing command to open files from cli

### ISSUE THREAD

**Issue by PierpaoloSpadafora** [git-learning-game/oh-my-git#212]
Currently, it is not possible to open files from the cli using a specific command.
This would greatly enhance the usability of the game, especially for who prefer to practice real world scenarios.

I expect to be able to open files from the CLI using a command, such as `vi <file_path>` or `open <file_path>`.

**Comment by defini-tiv** [comment]
you can already do that with `nano <filename>` or `fake-editor <filename>`

**Comment by PierpaoloSpadafora** [comment]
I was expecting to be able to open the in-game text editor, but none of them seemed to work

![Editor-Missing-Image](https://github.com/git-learning-game/oh-my-git/assets/75368540/cad8c23f-e572-4451-a63d-39e78867f535)

---

Then I tried with some of my local text editors but only `notepad <path_to_file>` worked for me.

**Oh My Git!** for Windows
**Version 0.6.5**
