### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by alefaut** [git-learning-game/oh-my-git#22]
On my laptop Dell latitude 7490 running Debian 10, as soon as the game is launched I see high CPU usage using top.

The oh-my-git process uses 20% of a CPU on main screen.
I saw it going up to 60% during one level.

**Comment by blinry** [comment]
Thanks for pointing that out! It's about the same for me, and I suspect it's a property of using a proper game engine for this kind of project. I guess other learning games, like "Human Resource Machine" for example, that run an ongoing game loop would behave similarly. Do you think that's a big problem?

In our case, the most resource-intensive part is the dynamic graph layouting. An approach that recognizes that there's not much layouting to be done, and freezes the nodes in place might help.

**Comment by alefaut** [comment]
In my opinion it's an issue, but I'm unable to fix it.
I opened this ticket so that you're aware.

I let you decide what to do about this information ;)
Completed all the steps and can says this project is quite cool and useful :)

**Comment by blinry** [comment]
Glad to hear that! Thanks! :)
