### ISSUE TITLE
Level "Rebasing" Baguette and Coffee branches mixed up

### ISSUE THREAD

**Issue by florianklumb** [git-learning-game/oh-my-git#41]
Oh my Git is really awesome. Thanks a lot for making it!

The screenshot explains the small but misleading but: ![image](https://user-images.githubusercontent.com/3025057/109934030-55d30f00-7ccc-11eb-8820-2f88e188a67c.png)

Pull request: https://github.com/git-learning-game/oh-my-git/pull/42

**Comment by blinry** [comment]
Fixed by #42.
