### ISSUE TITLE
[Question] Is there any plan for i18n?

### ISSUE THREAD

**Issue by frank-zsy** [git-learning-game/oh-my-git#55]
I am a student from China and I found the game very interesting and helpful for learning git.

Is there any plan for internationalization? Or is it feasible, I think I can help to translate the game into Chinese.

Thanks again for the great work!

**Comment by rolandog** [comment]
I think I could also help with Spanish translations.

**Comment by abitrolly** [comment]
It is feasible - https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html

However, it may be hard to review PRs and merge them, as the funding for the project is already over - https://ohmygit.org/

**Comment by frukto** [comment]
I will be arround for a german translation!

**Comment by frank-zsy** [comment]
> It is feasible - https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html
> 
> However, it may be hard to review PRs and merge them, as the funding for the project is already over - https://ohmygit.org/

Understood, I will fork the project and have a try.
