### ISSUE TITLE
Crash: Stash levels hang on Windows build

### ISSUE THREAD

**Issue by mundifex** [git-learning-game/oh-my-git#56]
Running Windows Version 20H2 (OS Build 19042.844), game Version 0.6.2. Reproducible with both packaged game downloaded from itch.io and within Godot engine editor running latest source from GitHub. Using the provided 'dependencies' folder in both instances.

Issuing the following command in level 'stash' causes the game to hang indefinitely:
`git stash push`

Loading level 'stash-pop' also hangs the game due to command `git stash push` in setup.

Function terminal::command_done plays $OkSound and emits signal "command_done" so the command itself appears to be completing successfully, at least on the backend. But something else never recovers and the game hangs to the point where it must be force killed.

**Comment by AlexDLSy** [comment]
I have the same issue. Exactly same behaviour. All of stash levels are affected.

**Comment by mundifex** [comment]
I have found the culprit: for whatever reason, the Windows git binary does not emit a newline character when executing `cat-file -p` against a stash ref. It _does_ emit a newline when running the same command against a main ref.

Using the 'stash' level for an environment:
```
$ git show-ref
21a9aa4241898a837817f2e0053b61501f172d70 refs/heads/main
5ac9410b6c8e72408ac59a2fc5f3131188e1c50a refs/stash

$ git cat-file -p 21a9;echo MAGIC
tree b591eec8a0e7e0a6cec044d0b73c56ebe63d8546
parent 4ff0eeedffa9bb8f1b01d6379b7f4b6227284a14
author You <you@time.agency> 1615439427 -0600
committer You <you@time.agency> 1615439427 -0600

Adding ingredients
MAGIC

$ git cat-file -p 5ac9;echo MAGIC
tree 97fe1d987c8edef22ae25174f21b169e3111c82b
parent 21a9aa4241898a837817f2e0053b61501f172d70
parent fb4f05aa2242c6981ce6ad94ac8923679c1e07f6
author You <you@time.agency> 1615439434 -0600
committer You <you@time.agency> 1615439434 -0600

WIP on main: 21a9aa4 Adding ingredientsMAGIC
```

The omission of the newline in the stash ref instance causes the Perl-based IPC client in **scripts/net-test** to enter an infinite loop because it never encounters the `MAGIC` terminator on a line by itself.

This occurs on the git binary included with the Windows itch.io build (version 2.28.0.windows.1) as well as the latest git binary from https://git-scm.com (version 2.30.2.windows.1).

**Comment by mundifex** [comment]
Fix for this submitted in https://github.com/git-learning-game/oh-my-git/pull/59
