### ISSUE TITLE
Git stash makes the game freeze on branching levels (on windows)

### ISSUE THREAD

**Issue by sorasful** [git-learning-game/oh-my-git#70]
Sometimes I update some files by accident, so I try to `git stash` them to reset my files but when I do so, the game crashes. I've tried on the first 2 levels of Branching.

I'm on Windows 10. 

Tell me if I can help more.

**Comment by AlexDLSy** [comment]
Your issue may be related to [this previous one.](https://github.com/git-learning-game/oh-my-git/issues/56)
Have you had a look at it ?
A pull request has been made by @mundifex but might cause big lag on some systems according to @blinry . So it may take some more time still.

But anyway it shows consistency with the analysis from @mundifex about this bug being triggered by stash command, and not being level-related.

**Comment by blinry** [comment]
Yeah, I think this is probably the same cause! Thanks for reporting, @sorasful! Hope we can get this fixed by improving #59! Closing this issue for now, as it's a duplicate.
