### ISSUE TITLE
wrong assumption about home directory

### ISSUE THREAD

**Issue by sibbi77** [git-learning-game/oh-my-git#81]
in line https://github.com/git-learning-game/oh-my-git/blob/b5ca69264afef5cbb44f7edda23170c6469db925/scenes/helpers.gd#L94 the game makes an assumption about the home directory of the user.
My home folder according to /etc/passwd is at /DATA/home/sebastian, which prevents the game from running.
On X11 it should be safe to rely on OS.get_environment("HOME")

**Comment by blinry** [comment]
Thanks, I agree! :)
