### ISSUE TITLE
Can the Discussion tab be enabled for this repository in order to discuss higher-level conceptual questions?

### ISSUE THREAD

**Issue by saulbaizman** [git-learning-game/oh-my-git#85]
Hi there,

This is a fantastic project! I have quite a lot of feedback to share and was wondering if the Discussion tab could be enabled on the repository.

Thanks!

Saul

CC: @DGiulietti

**Comment by blinry** [comment]
Thanks! :blush: Good idea, we enabled it! Discuss away!
