### ISSUE TITLE
remotes - Problems - win condition too specific

### ISSUE THREAD

**Issue by Gerrit-K** [git-learning-game/oh-my-git#87]
Almost everything worked as expected so far, but here I was really drawing a blank on what I'm doing wrong ... until I looked at the win condition in the source code. 

<details><summary>Spoiler</summary>

The condition to check for either green _*and*_ blue or _*turquoise*_ (?!) is too specific in my opinion. There are absolutely no hints that either one of these is expected. E.g. (in my opinion) totally valid solutions would also be:
- You accept the color of your friend
- You persuade your friend to accept your color
- You find a compromise in another color, e.g. red

I didn't even remotely think about turquoise (yes, I know it's the mixture of green and blue) and also not about a two-color solution. Absurdly, if you simply ignore the conflict and add the file as it is (with the conflict markers and both lines), it gets accepted 😅

</details>

The fact that I immediately came up with the correct solution (w.r.t. git), but struggled with it being accepted just because of the contents of the final result, which has almost nothing to do with learning git, was a bit frustrating.

**Comment by rol1** [comment]
I also tried to solve this task several times, but I failed. I don't have a clue what I'm doing wrong.

**Comment by kevinchee** [comment]
...and I was so certain of cyan. 🤨

**Comment by blinry** [comment]
That's fair, thanks for pointing this out! :) We simplified the win condition to accept all possible "compromises", just observing the shape of the commit graph. Do you think that's a good solution?

Cyan! <3
