### ISSUE TITLE
How to Start the Game???

### ISSUE THREAD

**Issue by kludikovsky** [git-learning-game/oh-my-git#91]
As this shall be for absolute beginners, there shall be a section for 
**'How to download and install'** (git clone, zip-download, sudo apt!!???, unpack/unzip)) and
'**How to start the game'** 
for each system (WIn, Linux, MacOs).

I have cloned it, but have no clue how to start it on MINT (which is also new to me).

**Comment by blinry** [comment]
Hi! In the README, there is a "Play the game!" section, which points to [the download page](https://blinry.itch.io/oh-my-git).

Do you have suggestions for how to make this even more clear?

**Comment by kludikovsky** [comment]
Under Windows you usually download a program, run an installer or unzip it and click onto the program name.
Under Linux and MacOS one usually installs a program using a packet manager (e.g. apt get install).

Here are just zip-files. And, as I have done, cloned the git repo.

So what I would expect, is a step by step (point by point) instruction like
* create a directory where to run the game (`$ mkdir omg`)
* change to the directory (`$ cd omg`)
* download the zip-file from here (click link)
*  unpack file into that directory (`$ unzip /downloads/oh-my-git`)
*  run the game (`$ ./oh-my-git`)

or something like that.

**Comment by blinry** [comment]
I tried to clarify this further for Linux on the [itch page](https://blinry.itch.io/oh-my-git)! All zip files should contain a high-level "oh-my-git" directory, so there's no need to create parent directories yourself. I also tried to accomodate people who use graphical file managers. Thanks! :)
